version: '3.8'

services:

  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    networks:
      - overlay
    ports:
      - "8000:80"

  productservice:
    image: ${DOCKER_REGISTRY-}productservice
    build:
      context: .
      dockerfile: ProductService/Dockerfile


  orderservice:
    image: ${DOCKER_REGISTRY-}orderservice
    build:
      context: .
      dockerfile: OrderService/Dockerfile
    networks:
      - overlay
    ports:
        - "8001:80"
  
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Emr@n_____"
      ACCEPT_EULA: "Y"
    ports:
       - "9000:1433"

networks:
  overlay:
